"""Scene list for the illustrated campaign: 20 per world, simple subjects first, rich scenes last."""

STYLE = ("16-bit retro video game pixel art, low resolution 64x64 sprite art upscaled with nearest neighbor, "
         "every pixel is a visible hard-edged square, no anti-aliasing, no gradients, limited 16-color palette, "
         "black 1-pixel outlines, cute, the scene fills the whole frame, no text.")
SIMPLE = "One big cute {s} in the center, filling most of the frame, simple plain background."
MEDIUM = "{s}, cute characters, simple background."
RICH = "{s}, detailed cozy full scene."

SCENES = {
 'meadow': ["smiling ladybug on a green leaf", "bee holding a little daisy", "happy snail on a red mushroom", "red apple with a green leaf and a tiny smiling worm", "green frog in a straw hat on a lily pad with a pink lotus",
   "White bunny holding a big carrot in a vegetable garden with a wooden fence", "Hedgehog carrying a red apple through tall grass", "Yellow chick hatching from an egg in a straw nest", "Butterfly over a field of daisies and poppies", "Three black ants with six legs and antennae carrying a giant strawberry across a checkered picnic blanket",
   "Mother duck and ducklings swimming in a pond with reeds", "Sunflower field under a smiling sun", "Mole popping out of a molehill in a vegetable garden", "Cozy cottage with a flower garden and a white picket fence", "Picnic basket with sandwiches, lemonade and cupcakes on a red checkered blanket",
   "Black ants having a picnic under a giant mushroom, tiny cups and cake", "Rainbow over a green meadow with fluffy sheep and flowers", "Beehive on a tree branch with bees and dripping honey", "Garden gnome watering tulips with a watering can", "Sunset meadow with fireflies, a little fox and wildflowers"],
 'forest': ["acorn with a smiling face and a leaf hat", "red toadstool mushroom with white dots", "round owl with big eyes on a branch at night", "squirrel holding a hazelnut", "hedgehog sheltering under a mushroom in the rain",
   "Sleepy red fox curled up on orange autumn leaves under an oak tree", "Bear cub hugging a honey pot in the forest", "Deer fawn in a sunny forest clearing", "Raccoon washing an apple in a forest stream", "Wooden log cabin in a pine forest with smoke from the chimney",
   "Beaver building a dam across a river", "Camping tent with a campfire under the stars in the forest", "Woodpecker knocking on a big tree trunk", "Badger family at the entrance of their burrow", "Forest stream with stepping stones, ferns and a frog",
   "Treehouse with a rope ladder in a big oak tree", "Moose drinking from a lake at sunset with pine trees", "Owl family in a hollow tree under a full moon", "Fox and rabbit sharing berries on a forest log", "Autumn forest path with glowing lanterns, mushrooms and falling leaves"],
 'sea': ["smiling orange starfish on the sand", "round pufferfish", "red crab waving its claws on the beach", "pink octopus wearing a little sailor hat", "blue whale spouting water",
   "Smiling turtle with sunglasses on a pink swim ring near a sandy beach with a palm tree", "Dolphin jumping over ocean waves at sunset", "Seahorse among colorful coral", "Glowing jellyfish in deep blue water", "Sandcastle with a flag, a bucket and a spade on the beach",
   "Clownfish hiding in a sea anemone", "Penguin standing on a small ice floe in the sea", "Pirate ship with black sails on the waves", "Underwater coral reef with many colorful fish", "Yellow submarine with a periscope underwater with fish",
   "Sea otter floating on its back holding a shell", "Beach with a palm tree, a striped umbrella and a beach ball", "Cat mermaid sitting on a rock in the sea", "Narwhal and a little boat in arctic waters", "Sunken treasure chest with gold coins, fish and seaweed on the sea floor"],
 'sweets': ["cupcake with pink frosting and a cherry", "pink donut with rainbow sprinkles", "ice cream cone with two scoops and a wafer", "swirly rainbow lollipop", "slice of strawberry layer cake on a plate",
   "Strawberry layer cake with candles, cupcakes and macarons on a pink tablecloth", "Gingerbread man with icing buttons", "Glass jar full of cookies", "Chocolate bar with a bite taken out and a smiling face", "Candy house with gumdrops and candy canes",
   "Stack of pancakes with syrup, butter and berries", "Strawberry milkshake with whipped cream and a straw", "Colorful macarons on a cake stand", "Teddy bear eating pink cotton candy", "Candy shop window with jars of sweets",
   "Birthday party table with a cake and balloons", "Cat baker holding a tray of croissants in a bakery", "Bubble tea cup with a cute face and tapioca pearls", "Ice cream truck on a sunny street", "Candy land with lollipop trees, gumdrop hills and a chocolate river"],
 'space': ["smiling planet with rings", "red and white rocket", "smiling crescent moon with stars", "little green alien waving", "flying saucer beaming up a cow",
   "Cat astronaut floating next to a ringed purple planet with stars", "Astronaut planting a flower on the moon", "Satellite orbiting the blue earth", "Comet with a rainbow tail among stars", "Little robot exploring red mars with rocks",
   "Alien family in a flying saucer", "Space station orbiting a planet", "Moon rover driving over craters with the earth in the sky", "Dog astronaut looking out of a rocket window", "Colorful galaxy with planets and stars",
   "Observatory with a big telescope on a hill at night", "Astronaut floating in space holding a balloon", "Rocket launching with clouds of smoke", "Aliens having a picnic on the moon", "Space city with glass domes and rockets on a planet"],
 'winter': ["big blue snowflake", "penguin wearing a red scarf", "snowman with a carrot nose and a top hat", "mug of hot cocoa with marshmallows", "polar bear cub on the snow",
   "Snowman with a red scarf in front of a cozy wooden cabin at night with a full moon", "Penguin ice skating on a frozen lake with snowy pine trees", "Red knitted mittens and a hat with a pompom", "Christmas tree with presents and lights", "Wooden sled on a snowy hill",
   "Arctic fox curled up in the snow", "Gingerbread house covered in snow", "Igloo with a child in a fur coat and a husky", "Reindeer with a glowing red nose", "Snowy village with lit windows at night",
   "Children having a snowball fight next to a snowman", "Penguin family on ice under the northern lights", "Santa sleigh with reindeer flying across the night sky", "Cozy fireplace with stockings and a sleeping cat", "Winter market with string lights, stalls and a carousel"],
 'fantasy': ["magic potion bottle glowing pink", "baby dragon", "white unicorn with a rainbow mane", "wizard hat with stars", "tiny fairy with sparkling wings",
   "Small purple dragon sitting on a pile of gold coins in a crystal cave", "Fairy tale castle on a green hill", "Mushroom house with a round door and windows", "Fiery phoenix bird spreading its wings", "Treasure chest overflowing with gems and gold",
   "Knight cat with a sword and shield", "Mermaid with a shell crown on a rock", "Witch cat flying on a broomstick past the moon", "Crystal cave with glowing purple crystals", "Enchanted forest with glowing mushrooms and fireflies",
   "Griffin standing on a mountain rock", "Wizard tower with a spiral roof and glowing windows", "Dragon sleeping curled around a castle tower", "Troll under a stone bridge over a river", "Floating island with waterfalls and a castle in the sky"],
 'harvest': ["orange pumpkin", "wicker basket full of red apples", "ear of yellow corn", "pink piglet", "cow with a cowbell",
   "Smiling pig driving a red tractor past a red barn and a windmill", "Fluffy sheep in a green meadow", "Rooster crowing on a wooden fence at sunrise", "Scarecrow in a golden wheat field", "Red barn with a windmill and hay bales",
   "Hen with fluffy yellow chicks", "Goat standing on a rocky hill", "Farm stand with crates of vegetables", "Brown horse in a stable", "Ducks swimming in a farm pond",
   "Apple orchard with a wooden ladder and baskets", "Hay wagon loaded with pumpkins", "Farmer cat harvesting carrots", "Sunflower field with bees and a farmhouse", "Farm at sunset with a cow, a pig, chickens and a barn"],
 'safari': ["lion cub", "giraffe", "zebra", "grey elephant", "hippo in the water",
   "Baby elephant spraying water at a watering hole with a giraffe and acacia trees", "Monkey swinging on a jungle vine", "Colorful parrot on a branch", "Rhino in the savanna", "Pink flamingos in a lagoon",
   "Crocodile in a river with water lilies", "Toucan on a tropical branch", "Cheetah running across the savanna", "Kangaroo with a joey in its pouch", "Safari jeep with binoculars on the savanna",
   "Jungle waterfall with tropical plants and birds", "Gorilla family in the jungle", "Meerkat family standing on watch", "Savanna sunset with acacia trees and giraffes", "Jungle river with a small boat, hippos and birds"],
 'harbor': ["anchor with a rope", "white sailboat", "red and white lighthouse", "seagull holding a fish", "red tugboat",
   "Red and white lighthouse on rocks at sunset with a fishing boat and seagulls", "Steam locomotive with puffs of smoke", "Red double-decker bus", "Harbor crane loading colorful containers onto a ship", "Fishing boat with nets and seagulls",
   "Ferry carrying cars across the bay", "Yellow tram on a city street", "Bicycle with a basket of flowers", "Seaside cafe with striped umbrellas", "Cargo ship sailing on the sea",
   "Fish market stall with fresh fish", "Colorful harbor houses by the water", "Cat lighthouse keeper with a lantern", "Carousel on a seaside pier", "Harbor at night with lights, boats and a lighthouse"],
 'market': ["croissant", "slice of pepperoni pizza", "burger with cheese and lettuce", "taco", "plate of sushi",
   "Market fruit stand with a striped awning and crates of fruit", "Bakery shelf with bread and baguettes", "Bowl of noodles with chopsticks", "Coffee cup with heart latte art", "Cheese shop with wheels of cheese",
   "Flower stall with buckets of tulips and roses", "Vegetable stand with tomatoes, carrots and cabbages", "Hot dog cart with an umbrella", "Panda eating ramen at a street food stall with red lanterns", "Bamboo basket of dumplings with steam",
   "Street food stall with paper lanterns and a cook", "Fish seller at a market stall", "Candy apple stand at a fair", "Busy market street with stalls and awnings", "Night market with lanterns and food stalls"],
 'workshop': ["paintbrush and paint palette", "acoustic guitar", "teddy bear", "toy robot", "kitten playing with a ball of yarn",
   "Little robot painting a sunflower on an easel in an art studio", "Wooden toy train on tracks", "Violin and bow", "Grand piano with music notes", "Sewing machine with fabric and buttons",
   "Toolbox with a hammer, saw and wrench", "Clockmaker desk with gears and a magnifying glass", "Colorful kite flying in the wind", "Vintage camera", "Pottery wheel with a clay vase",
   "Beaver carpenter building a wooden chair", "Toy shop window with dolls and toys", "Band of animals playing music instruments", "Inventor lab with gadgets and light bulbs", "Cozy art studio with paintings and a cat"],
 'sky': ["fluffy cloud with a smile", "hot air balloon with rainbow stripes", "paper airplane", "diamond kite with a long tail", "rainbow with clouds",
   "Hot air balloon flying over green hills and a winding river", "Propeller airplane flying through clouds", "Red helicopter in the blue sky", "Eagle soaring over mountains", "Castle on top of the clouds",
   "Parachutist with a colorful parachute", "Zeppelin airship among clouds", "Windmill on a grassy hill with clouds", "Stork carrying a bundle through the sky", "Many hot air balloons at a balloon festival",
   "Cable car over snowy mountains", "Stormy sky with lightning over a little house", "Floating islands with trees connected by bridges", "Sunset over mountains with a flock of birds", "Sky city with airships and floating houses"],
 'festival': ["red paper lantern", "colorful firework burst", "bunch of colorful balloons", "lucky cat waving its paw", "carousel horse",
   "Ferris wheel at a fair with lights", "Striped circus tent with flags", "Koi pond with floating lanterns", "Chinese dragon dance in the street", "Big birthday cake with candles and sparklers",
   "Band playing music on a festival stage", "Halloween night with glowing pumpkin lanterns", "Bouquet of flowers in a vase", "Cherry blossom festival with lanterns", "Parade float decorated with flowers",
   "Magician rabbit coming out of a top hat", "Fireworks over a city at night", "Amusement park with a roller coaster", "Lantern festival with sky lanterns over a river", "Carnival at night with a ferris wheel, stalls and lights"],
}


def prompt(world: str, i: int) -> str:
    s = SCENES[world][i]
    tpl = SIMPLE if i < 5 else (RICH if i >= 15 else MEDIUM)
    return tpl.format(s=s) + ' ' + STYLE

# Level titles, "English|Русский", in the same order as SCENES.
NAMES = {
 'meadow': "Ladybug|Божья коровка;Busy Bee|Пчёлка;Snail on a Mushroom|Улитка на грибе;Apple and Worm|Яблоко с червячком;Frog on a Lily Pad|Лягушка на кувшинке;Bunny and Carrot|Зайка с морковкой;Hedgehog with an Apple|Ёжик с яблоком;New Chick|Цыплёнок;Butterfly Field|Бабочка над лугом;Ants and Strawberry|Муравьи и клубника;Duck Family|Утиное семейство;Sunflower Field|Подсолнухи;Garden Mole|Крот в огороде;Garden Cottage|Домик с садом;Picnic Basket|Корзинка для пикника;Ant Tea Party|Чаепитие муравьёв;Rainbow Meadow|Радужный луг;Beehive|Улей;Garden Gnome|Садовый гном;Fireflies at Sunset|Светлячки на закате",
 'forest': "Little Acorn|Жёлудь;Toadstool|Мухомор;Night Owl|Сова;Squirrel|Белочка;Rainy Hedgehog|Ёжик под дождём;Sleepy Fox|Лис в листве;Honey Bear|Мишка с мёдом;Fawn|Оленёнок;Raccoon|Енот у ручья;Log Cabin|Избушка в лесу;Beaver Dam|Бобровая плотина;Campfire Night|Костёр под звёздами;Woodpecker|Дятел;Badger Family|Семья барсуков;Forest Stream|Лесной ручей;Treehouse|Домик на дереве;Moose at Sunset|Лось на закате;Owl Family|Совиное семейство;Berry Friends|Лис и заяц;Lantern Path|Тропа с фонариками",
 'sea': "Starfish|Морская звезда;Pufferfish|Рыба-ёж;Crab|Краб;Sailor Octopus|Осьминог-матрос;Whale|Кит;Turtle on a Ring|Черепаха на круге;Dolphin|Дельфин;Seahorse|Морской конёк;Jellyfish|Медуза;Sandcastle|Замок из песка;Clownfish|Рыба-клоун;Penguin on Ice|Пингвин на льдине;Pirate Ship|Пиратский корабль;Coral Reef|Коралловый риф;Yellow Submarine|Жёлтая подлодка;Sea Otter|Морская выдра;Beach Day|День на пляже;Cat Mermaid|Кошка-русалка;Narwhal|Нарвал;Sunken Treasure|Сокровища на дне",
 'sweets': "Cupcake|Капкейк;Donut|Пончик;Ice Cream|Мороженое;Lollipop|Леденец;Strawberry Cake|Клубничный торт;Party Cake|Праздничный торт;Gingerbread Man|Пряничный человечек;Cookie Jar|Банка печенья;Chocolate Bar|Шоколадка;Candy House|Конфетный домик;Pancakes|Блинчики;Milkshake|Молочный коктейль;Macarons|Макаруны;Cotton Candy|Сахарная вата;Candy Shop|Магазин сладостей;Birthday Party|День рождения;Cat Baker|Кот-пекарь;Bubble Tea|Бабл-ти;Ice Cream Truck|Фургон мороженого;Candy Land|Конфетная страна",
 'space': "Ringed Planet|Планета с кольцами;Rocket|Ракета;Crescent Moon|Месяц;Little Alien|Инопланетянин;Saucer and Cow|Тарелка и корова;Cat Astronaut|Кот-космонавт;Moon Garden|Цветок на Луне;Satellite|Спутник;Rainbow Comet|Радужная комета;Mars Robot|Робот на Марсе;Alien Family|Семья пришельцев;Space Station|Космическая станция;Moon Rover|Луноход;Space Dog|Пёс-космонавт;Galaxy|Галактика;Observatory|Обсерватория;Balloon in Space|Шарик в космосе;Launch Day|Старт ракеты;Moon Picnic|Пикник на Луне;Space City|Космический город",
 'winter': "Snowflake|Снежинка;Penguin|Пингвин;Snowman|Снеговик;Hot Cocoa|Какао;Polar Bear Cub|Медвежонок;Snowman at the Cabin|Снеговик у избушки;Skating Penguin|Пингвин на катке;Mittens|Варежки;Christmas Tree|Ёлка;Sled|Санки;Arctic Fox|Песец;Gingerbread House|Пряничный домик;Igloo|Иглу;Red-Nosed Reindeer|Олень;Snowy Village|Зимняя деревня;Snowball Fight|Игра в снежки;Northern Lights|Северное сияние;Santa's Sleigh|Сани Деда Мороза;Fireplace|У камина;Winter Market|Зимняя ярмарка",
 'fantasy': "Magic Potion|Волшебное зелье;Baby Dragon|Дракончик;Unicorn|Единорог;Wizard Hat|Шляпа волшебника;Fairy|Фея;Dragon's Gold|Дракончик и золото;Castle|Замок;Mushroom House|Грибной домик;Phoenix|Феникс;Treasure Chest|Сундук с сокровищами;Knight Cat|Кот-рыцарь;Mermaid|Русалка;Witch Cat|Кошка-ведьма;Crystal Cave|Хрустальная пещера;Enchanted Forest|Волшебный лес;Griffin|Грифон;Wizard Tower|Башня мага;Sleeping Dragon|Спящий дракон;Troll Bridge|Мост тролля;Floating Island|Летающий остров",
 'harvest': "Pumpkin|Тыква;Apple Basket|Корзина яблок;Corn|Кукуруза;Piglet|Поросёнок;Cow|Корова;Tractor Pig|Хрюша на тракторе;Sheep|Овечка;Rooster|Петух;Scarecrow|Пугало;Red Barn|Красный амбар;Hen and Chicks|Курица с цыплятами;Mountain Goat|Козочка;Farm Stand|Овощной прилавок;Horse|Лошадка;Farm Pond|Утиный пруд;Apple Orchard|Яблоневый сад;Hay Wagon|Телега с тыквами;Farmer Cat|Кот-фермер;Sunflower Farm|Ферма подсолнухов;Farm at Sunset|Ферма на закате",
 'safari': "Lion Cub|Львёнок;Giraffe|Жираф;Zebra|Зебра;Elephant|Слон;Hippo|Бегемот;Watering Hole|Слонёнок у водопоя;Monkey|Обезьянка;Parrot|Попугай;Rhino|Носорог;Flamingos|Фламинго;Crocodile|Крокодил;Toucan|Тукан;Cheetah|Гепард;Kangaroo|Кенгуру;Safari Jeep|Сафари;Jungle Waterfall|Водопад в джунглях;Gorillas|Гориллы;Meerkats|Сурикаты;Savanna Sunset|Закат в саванне;Jungle River|Река в джунглях",
 'harbor': "Anchor|Якорь;Sailboat|Парусник;Lighthouse|Маяк;Seagull|Чайка;Tugboat|Буксир;Lighthouse at Sunset|Маяк на закате;Steam Train|Паровоз;Double-Decker|Двухэтажный автобус;Harbor Crane|Портовый кран;Fishing Boat|Рыбацкая лодка;Ferry|Паром;Tram|Трамвай;Bicycle|Велосипед;Seaside Cafe|Кафе у моря;Cargo Ship|Грузовой корабль;Fish Market|Рыбный рынок;Harbor Houses|Домики в гавани;Lighthouse Keeper|Кот-смотритель;Pier Carousel|Карусель на пирсе;Harbor at Night|Ночная гавань",
 'market': "Croissant|Круассан;Pizza|Пицца;Burger|Бургер;Taco|Тако;Sushi|Суши;Fruit Stand|Фруктовая лавка;Bakery|Пекарня;Noodles|Лапша;Latte|Латте;Cheese Shop|Сырная лавка;Flower Stall|Цветочный киоск;Vegetable Stand|Овощная лавка;Hot Dog Cart|Хот-доги;Panda and Ramen|Панда и рамен;Dumplings|Пельмени;Street Food|Уличная еда;Fishmonger|Рыбная лавка;Candy Apples|Яблоки в карамели;Market Street|Рыночная улица;Night Market|Ночной рынок",
 'workshop': "Paint Palette|Палитра;Guitar|Гитара;Teddy Bear|Плюшевый мишка;Toy Robot|Игрушечный робот;Kitten and Yarn|Котёнок и клубок;Robot Painter|Робот-художник;Toy Train|Игрушечный поезд;Violin|Скрипка;Grand Piano|Рояль;Sewing Machine|Швейная машинка;Toolbox|Ящик инструментов;Clockmaker|Часовщик;Kite|Воздушный змей;Camera|Фотоаппарат;Pottery|Гончарный круг;Beaver Carpenter|Бобр-столяр;Toy Shop|Магазин игрушек;Animal Band|Звериный оркестр;Inventor's Lab|Лаборатория изобретателя;Art Studio|Мастерская художника",
 'sky': "Happy Cloud|Облачко;Rainbow Balloon|Радужный шар;Paper Plane|Бумажный самолётик;Kite|Воздушный змей;Rainbow|Радуга;Balloon over the Hills|Шар над холмами;Airplane|Самолёт;Helicopter|Вертолёт;Eagle|Орёл;Cloud Castle|Замок в облаках;Parachute|Парашют;Airship|Дирижабль;Windmill|Мельница;Stork|Аист;Balloon Festival|Фестиваль шаров;Cable Car|Канатная дорога;Thunderstorm|Гроза;Floating Islands|Летающие острова;Mountain Sunset|Закат в горах;Sky City|Небесный город",
 'festival': "Paper Lantern|Фонарик;Firework|Салют;Balloons|Шарики;Lucky Cat|Манэки-нэко;Carousel Horse|Лошадка с карусели;Ferris Wheel|Колесо обозрения;Circus Tent|Цирк;Koi Pond|Пруд с карпами;Dragon Dance|Танец дракона;Birthday Cake|Торт со свечами;Festival Band|Концерт;Halloween Night|Хэллоуин;Bouquet|Букет;Cherry Blossoms|Сакура;Flower Parade|Цветочный парад;Magic Rabbit|Кролик фокусника;City Fireworks|Салют над городом;Amusement Park|Парк аттракционов;Lantern Festival|Праздник фонарей;Night Carnival|Ночной карнавал",
}
NAMES = {w: [tuple(x.split('|')) for x in v.split(';')] for w, v in NAMES.items()}


if __name__ == '__main__':
    # Job queue for generate.py: two variants (seeds) of every scene, worlds interleaved.
    import json
    for seed in (11, 23):
        for i in range(20):
            for w in SCENES:
                print(json.dumps({'id': f'{w}-{i + 1:02d}-s{seed}', 'seed': seed, 'prompt': prompt(w, i)}))
