/**
 * Extracts a few Microsoft Fluent Emoji (Flat, MIT license) as inline SVG strings for the UI.
 * Run: bun scripts/build-icons.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = [
  'light-bulb', 'magnet', 'coin', 'star', 'glowing-star', 'locked', 'fire', 'trophy', 'crown', 'gem-stone',
  'wrapped-gift', 'ant', 'sparkles', 'snowflake', 'link', 'red-question-mark', 'speaker-high-volume',
  'muted-speaker', 'musical-note', 'gear', 'house', 'world-map', 'framed-picture', 'package', 'skull',
  'party-popper', 'money-bag', 'check-mark-button', 'cross-mark', 'artist-palette', 'four-leaf-clover',
  'shooting-star', 'lady-beetle', 'sun', 'key', 'hourglass-done', 'construction', 'door',
  // shop
  'shopping-bags', 'billed-cap', 'top-hat', 'ribbon', 'sunglasses', 'santa-claus', 'hut', 'wood', 'ice',
  'jack-o-lantern', 'game-die',
  // map decorations
  'mushroom', 'evergreen-tree', 'deciduous-tree', 'tulip', 'sunflower', 'blossom', 'spiral-shell', 'tropical-fish',
  'lollipop', 'candy', 'doughnut', 'crescent-moon', 'ringed-planet', 'rocket', 'snowman', 'crystal-ball', 'castle',
  'cherry-blossom', 'herb', 'fallen-leaf', 'maple-leaf', 'palm-tree', 'shortcake', 'cupcake', 'comet',
  'christmas-tree', 'unicorn', 'butterfly', 'honeybee', 'snail', 'seedling', 'crab', 'cookie', 'ice-cream',
  'cloud-with-snow', 'magic-wand', 'chestnut',
];

const set = JSON.parse(readFileSync('node_modules/@iconify-json/fluent-emoji-flat/icons.json', 'utf8'));
const out: Record<string, string> = {};
for (const name of ICONS) {
  let icon = set.icons[name];
  let key = name;
  if (!icon && set.aliases?.[name]) {
    key = set.aliases[name].parent;
    icon = set.icons[key];
  }
  if (!icon) throw new Error('missing icon ' + name);
  const w = icon.width ?? set.width;
  const h = icon.height ?? set.height;
  out[name] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${icon.left ?? 0} ${icon.top ?? 0} ${w} ${h}">${icon.body}</svg>`;
}
const src =
  '// Generated by scripts/build-icons.ts from Microsoft Fluent Emoji (Flat), MIT License.\n' +
  '// https://github.com/microsoft/fluentui-emoji\n' +
  `export const EMOJI = ${JSON.stringify(out, null, 0)} as const;\n` +
  'export type EmojiName = keyof typeof EMOJI;\n';
writeFileSync('src/ui/emoji.generated.ts', src);
console.log('wrote', Object.keys(out).length, 'icons,', src.length, 'bytes');
