import type { PictureEntry } from './pictures-manifest';

/** Fresh subjects for worlds 8–14. All art comes from the already bundled open emoji sets. */
type Row = [icon: string, en: string, ru: string, source?: 'fluent' | 'twemoji' | 'noto'];
const rows = {
  harvest: [
    ['sheaf-of-rice', 'Golden Harvest', 'Золотой урожай'],
    ['grapes', 'Grapevine', 'Виноградная лоза'],
    ['pear', 'Orchard Pear', 'Груша из сада'],
    ['red-apple', 'Orchard Apple', 'Садовое яблоко'],
    ['cow', 'Dairy Cow', 'Корова'],
    ['pig', 'Farm Pig', 'Поросёнок'],
    ['ewe', 'Woolly Sheep', 'Пушистая овечка'],
    ['goat', 'Hilltop Goat', 'Козочка'],
    ['horse', 'Chestnut Horse', 'Гнедая лошадь'],
    ['duck', 'Pond Duck', 'Утка у пруда'],
    ['turkey', 'Turkey', 'Индюк'],
    ['hatching-chick', 'New Arrival', 'Птенчик'],
    ['sunflower', 'Sunflower Patch', 'Подсолнухи'],
    ['carrot', 'Carrot Patch', 'Морковная грядка'],
    ['broccoli', 'Broccoli', 'Брокколи'],
    ['garlic', 'Garlic Bulb', 'Чеснок'],
    ['onion', 'Garden Onion', 'Лук'],
    ['potato', 'Potato Harvest', 'Картофель'],
    ['bell-pepper', 'Bell Pepper', 'Сладкий перец'],
    ['basket', 'Harvest Basket', 'Корзина урожая'],
    ['tractor', 'Field Tractor', 'Трактор в поле', 'fluent'],
    ['ear-of-corn', 'Sweet Corn', 'Сахарная кукуруза'],
    ['lemon', 'Lemon Grove', 'Лимонная роща'],
    ['cherries', 'Cherry Harvest', 'Урожай вишни'],
  ],
  safari: [
    ['elephant', 'Elephant', 'Слон'],
    ['giraffe', 'Giraffe', 'Жираф'],
    ['zebra', 'Zebra', 'Зебра'],
    ['rhinoceros', 'Rhinoceros', 'Носорог'],
    ['hippopotamus', 'River Hippo', 'Бегемот'],
    ['crocodile', 'Crocodile', 'Крокодил'],
    ['gorilla', 'Gorilla', 'Горилла'],
    ['orangutan', 'Orangutan', 'Орангутан'],
    ['monkey', 'Jungle Monkey', 'Обезьяна в джунглях'],
    ['leopard', 'Leopard', 'Леопард'],
    ['tiger', 'Tiger Trail', 'Тигр на тропе'],
    ['lion', 'Savanna Lion', 'Лев саванны'],
    ['camel', 'Desert Camel', 'Верблюд'],
    ['two-hump-camel', 'Bactrian Camel', 'Двугорбый верблюд'],
    ['kangaroo', 'Kangaroo', 'Кенгуру'],
    ['sloth', 'Sleepy Sloth', 'Сонный ленивец'],
    ['peacock', 'Peacock Fan', 'Павлиний веер', 'fluent'],
    ['parrot', 'Jungle Parrot', 'Попугай джунглей', 'fluent'],
    ['flamingo', 'Lagoon Flamingo', 'Фламинго в лагуне', 'fluent'],
    ['palm-tree', 'Jungle Palm', 'Пальма в джунглях'],
    ['turtle', 'River Turtle', 'Речная черепаха', 'fluent'],
    ['snake', 'Jungle Snake', 'Змея джунглей'],
    ['lizard', 'Sunbathing Lizard', 'Ящерица'],
    ['cactus', 'Desert Cactus', 'Кактус'],
  ],
  harbor: [
    ['sailboat', 'Harbor Sailboat', 'Парусник в гавани'],
    ['ship', 'Ocean Liner', 'Океанский лайнер'],
    ['speedboat', 'Speedboat', 'Катер'],
    ['canoe', 'Quiet Canoe', 'Каноэ'],
    ['ferry', 'Island Ferry', 'Паром'],
    ['anchor', 'Old Anchor', 'Старый якорь'],
    ['ring-buoy', 'Harbor Lifebuoy', 'Спасательный круг'],
    ['fishing-pole', 'Fishing Trip', 'Рыбалка'],
    ['compass', 'Compass Rose', 'Компас'],
    ['world-map', 'Sailing Map', 'Карта мореплавателя'],
    ['locomotive', 'Steam Train', 'Паровоз'],
    ['tram', 'Harbor Tram', 'Трамвай'],
    ['bus', 'Coastal Bus', 'Прибрежный автобус'],
    ['bicycle', 'Seaside Bicycle', 'Велосипед'],
    ['motor-scooter', 'Little Scooter', 'Скутер'],
    ['pickup-truck', 'Delivery Truck', 'Пикап'],
    ['automobile', 'Coastal Drive', 'Машина у моря'],
    ['houses', 'Harbor Houses', 'Домики гавани'],
    ['post-office', 'Post Office', 'Почта'],
    ['department-store', 'Department Store', 'Универмаг'],
    ['fountain', 'Town Fountain', 'Городской фонтан'],
    ['bridge-at-night', 'Harbor Bridge', 'Мост в гавани', 'fluent'],
    ['railway-car', 'Railway Car', 'Вагон'],
    ['articulated-lorry', 'Cargo Delivery', 'Грузовик'],
  ],
  market: [
    ['croissant', 'Warm Croissant', 'Круассан'],
    ['baguette-bread', 'Fresh Baguette', 'Багет'],
    ['pretzel', 'Pretzel Stand', 'Крендель'],
    ['bagel', 'Sesame Bagel', 'Бейгл'],
    ['waffle', 'Golden Waffle', 'Вафля'],
    ['sandwich', 'Lunch Sandwich', 'Сэндвич'],
    ['stuffed-flatbread', 'Stuffed Flatbread', 'Лепёшка с начинкой'],
    ['burrito', 'Burrito', 'Буррито'],
    ['taco', 'Taco Stand', 'Тако'],
    ['falafel', 'Falafel', 'Фалафель'],
    ['steaming-bowl', 'Noodle Bowl', 'Лапша'],
    ['curry-rice', 'Curry Rice', 'Рис с карри'],
    ['spaghetti', 'Spaghetti', 'Спагетти'],
    ['dumpling', 'Dumpling', 'Пельмешек'],
    ['sushi', 'Sushi Platter', 'Суши'],
    ['fried-shrimp', 'Crispy Shrimp', 'Креветка в кляре'],
    ['teapot', 'Afternoon Tea', 'Чаепитие'],
    ['teacup-without-handle', 'Green Tea', 'Зелёный чай'],
    ['bubble-tea', 'Bubble Tea', 'Бабл-ти'],
    ['mate', 'Yerba Mate', 'Мате'],
    ['cup-with-straw', 'Summer Lemonade', 'Лимонад'],
    ['pineapple', 'Pineapple Stall', 'Ананас'],
    ['mango', 'Ripe Mango', 'Манго'],
    ['coconut', 'Fresh Coconut', 'Кокос'],
  ],
  workshop: [
    ['artist-palette', 'Paint Palette', 'Палитра художника'],
    ['guitar', 'Electric Guitar', 'Электрогитара'],
    ['violin', 'Violin', 'Скрипка'],
    ['trumpet', 'Brass Trumpet', 'Труба'],
    ['saxophone', 'Saxophone', 'Саксофон'],
    ['accordion', 'Accordion', 'Аккордеон'],
    ['drum', 'Toy Drum', 'Барабан'],
    ['banjo', 'Banjo', 'Банджо'],
    ['musical-keyboard', 'Piano Keys', 'Клавиши пианино'],
    ['camera', 'Camera', 'Фотоаппарат'],
    ['movie-camera', 'Movie Camera', 'Кинокамера'],
    ['telephone', 'Retro Telephone', 'Ретро-телефон'],
    ['radio', 'Workshop Radio', 'Радио'],
    ['sewing-needle', 'Needle and Thread', 'Иголка с ниткой'],
    ['thread', 'Spool of Thread', 'Катушка ниток'],
    ['yarn', 'Ball of Yarn', 'Клубок пряжи'],
    ['toolbox', 'Toolbox', 'Ящик инструментов'],
    ['paintbrush', 'Paintbrush', 'Кисточка'],
    ['teddy-bear', 'Handmade Teddy', 'Плюшевый медведь'],
    ['kite', 'Patchwork Kite', 'Воздушный змей'],
    ['yo-yo', 'Yo-Yo', 'Йо-йо'],
    ['video-game', 'Game Controller', 'Геймпад'],
    ['puzzle-piece', 'Jigsaw Piece', 'Часть пазла'],
    ['abacus', 'Abacus', 'Счёты'],
  ],
  sky: [
    ['airplane', 'Cloud Hopper', 'Самолёт'],
    ['small-airplane', 'Little Plane', 'Маленький самолёт'],
    ['helicopter', 'Helicopter', 'Вертолёт'],
    ['parachute', 'Parachute', 'Парашют'],
    ['eagle', 'Soaring Eagle', 'Парящий орёл'],
    ['dove', 'White Dove', 'Белый голубь'],
    ['swan', 'White Swan', 'Белый лебедь'],
    ['butterfly', 'Sky Butterfly', 'Бабочка в небе'],
    ['bird', 'Songbird', 'Певчая птица'],
    ['rainbow', 'Rainbow Arch', 'Радужная арка'],
    ['sun-behind-rain-cloud', 'Sun Shower', 'Солнечный дождь'],
    ['cloud-with-lightning-and-rain', 'Summer Storm', 'Летняя гроза'],
    ['umbrella-with-rain-drops', 'Rainy Walk', 'Прогулка под дождём'],
    ['wind-face', 'Mountain Breeze', 'Горный ветер'],
    ['tornado', 'Whirlwind', 'Вихрь'],
    ['mountain', 'Mountain Trail', 'Горная тропа'],
    ['mount-fuji', 'Mount Fuji', 'Фудзияма'],
    ['aerial-tramway', 'Sky Tram', 'Воздушный трамвай'],
    ['suspension-railway', 'Suspended Railway', 'Подвесная дорога'],
    ['ferris-wheel', 'Above the Clouds', 'Над облаками', 'fluent'],
    ['satellite-antenna', 'Listening to Space', 'Спутниковая антенна'],
    ['telescope', 'Stargazing', 'Наблюдение за звёздами'],
    ['ringed-planet', 'Distant Planet', 'Далёкая планета', 'twemoji'],
    ['shooting-star', 'Wish Upon a Star', 'Загадай желание'],
  ],
  festival: [
    ['cherry-blossom', 'Cherry Blossom', 'Цветущая сакура'],
    ['hibiscus', 'Festival Hibiscus', 'Праздничный гибискус'],
    ['tulip', 'Spring Tulip', 'Весенний тюльпан'],
    ['rose', 'Garden Rose', 'Садовая роза'],
    ['bouquet', 'Flower Bouquet', 'Букет'],
    ['lotus', 'Lotus Pond', 'Пруд с лотосами'],
    ['potted-plant', 'Garden Pot', 'Цветок в горшке'],
    ['red-paper-lantern', 'Paper Lantern', 'Бумажный фонарь'],
    ['wind-chime', 'Wind Chime', 'Музыка ветра'],
    ['carp-streamer', 'Carp Streamers', 'Карпы на ветру'],
    ['tanabata-tree', 'Wishing Tree', 'Дерево желаний'],
    ['pine-decoration', 'New Year Welcome', 'Новогоднее украшение'],
    ['japanese-dolls', 'Festival Dolls', 'Праздничные куклы'],
    ['folding-hand-fan', 'Silk Fan', 'Шёлковый веер'],
    ['kimono', 'Festival Kimono', 'Праздничное кимоно'],
    ['ballet-shoes', 'Ballet Shoes', 'Балетные туфельки'],
    ['performing-arts', 'Theatre Masks', 'Театральные маски'],
    ['circus-tent', 'Festival Circus', 'Праздничный цирк', 'twemoji'],
    ['ferris-wheel', 'Festival Wheel', 'Колесо праздника', 'twemoji'],
    ['roller-coaster', 'Festival Ride', 'Праздничные горки', 'fluent'],
    ['fireworks', 'Fireworks Finale', 'Праздничный салют', 'fluent'],
    ['sparkler', 'Sparkler', 'Бенгальский огонь'],
    ['japanese-castle', 'Lantern Castle', 'Замок фонарей', 'twemoji'],
    ['wedding', 'Garden Chapel', 'Часовня в саду'],
  ],
} satisfies Partial<Record<PictureEntry['theme'], Row[]>>;

export const EXPANSION_PICTURES: PictureEntry[] = Object.entries(rows).flatMap(([theme, entries]) =>
  (entries as Row[]).map(([icon, en, ru, source = 'noto']) => ({
    id: `${theme}-${icon}`, source, icon, theme: theme as PictureEntry['theme'],
    name: { en, ru }, complexity: 2,
  })),
);
