/**
 * Curated list of emoji used as level pictures.
 *
 * Every entry was checked visually on the contact sheets produced by scripts/build-pictures.ts
 * (20x20 / 5 colors and 32x32 / 8 colors + background). When a subject exists in both sets we keep
 * the version that pixelizes better; for a few popular subjects both are included (the Twemoji one
 * gets a `tw-` id prefix).
 *
 * complexity: 1 = bold simple shape with few colors, reads even at 16x16 (first levels of a world);
 *             2 = medium detail, good at 20–32; 3 = detailed scene/object, wants 32–48.
 */

export interface PictureEntry {
  id: string;
  source: 'fluent' | 'twemoji' | 'noto';
  icon: string;
  theme: 'meadow' | 'forest' | 'sea' | 'sweets' | 'space' | 'winter' | 'fantasy';
  name: { en: string; ru: string };
  complexity: 1 | 2 | 3;
}

type Theme = PictureEntry['theme'];
type Row = [id: string, source: 'f' | 't' | 'n', icon: string, en: string, ru: string, complexity: 1 | 2 | 3];

const rows: Record<Theme, Row[]> = {
  meadow: [
    ['red-apple', 't', 'red-apple', 'Apple', 'Яблоко', 1],
    ['green-apple', 'f', 'green-apple', 'Green Apple', 'Зелёное яблоко', 1],
    ['cherries', 'f', 'cherries', 'Cherries', 'Вишенки', 1],
    ['strawberry', 'f', 'strawberry', 'Strawberry', 'Клубника', 1],
    ['tangerine', 't', 'tangerine', 'Tangerine', 'Мандарин', 1],
    ['lemon', 't', 'lemon', 'Lemon', 'Лимон', 1],
    ['tomato', 'f', 'tomato', 'Tomato', 'Помидор', 1],
    ['carrot', 't', 'carrot', 'Carrot', 'Морковка', 1],
    ['eggplant', 'f', 'eggplant', 'Eggplant', 'Баклажан', 1],
    ['tulip', 'f', 'tulip', 'Tulip', 'Тюльпан', 1],
    ['rose', 't', 'rose', 'Rose', 'Роза', 1],
    ['four-leaf-clover', 'f', 'four-leaf-clover', 'Clover', 'Клевер', 1],
    ['lady-beetle', 'f', 'lady-beetle', 'Ladybug', 'Божья коровка', 1],
    ['sun', 'f', 'sun', 'Sun', 'Солнышко', 1],
    ['seedling', 'f', 'seedling', 'Sprout', 'Росток', 1],
    ['watermelon', 'f', 'watermelon', 'Watermelon', 'Арбуз', 2],
    ['banana', 'f', 'banana', 'Banana', 'Банан', 2],
    ['peach', 't', 'peach', 'Peach', 'Персик', 2],
    ['kiwi-fruit', 'f', 'kiwi-fruit', 'Kiwi', 'Киви', 2],
    ['ear-of-corn', 'f', 'ear-of-corn', 'Corn', 'Кукуруза', 2],
    ['avocado', 'f', 'avocado', 'Avocado', 'Авокадо', 2],
    ['sunflower', 't', 'sunflower', 'Sunflower', 'Подсолнух', 2],
    ['hibiscus', 'f', 'hibiscus', 'Hibiscus', 'Гибискус', 2],
    ['cherry-blossom', 't', 'cherry-blossom', 'Sakura', 'Сакура', 2],
    ['honeybee', 'f', 'honeybee', 'Bee', 'Пчёлка', 2],
    ['butterfly', 't', 'butterfly', 'Butterfly', 'Бабочка', 2],
    ['snail', 't', 'snail', 'Snail', 'Улитка', 2],
    ['caterpillar', 'f', 'bug', 'Caterpillar', 'Гусеница', 2],
    ['baby-chick', 'f', 'baby-chick', 'Chick', 'Цыплёнок', 2],
    ['frog', 'f', 'frog', 'Frog', 'Лягушка', 2],
    ['rainbow', 'f', 'rainbow', 'Rainbow', 'Радуга', 2],
    ['rabbit-face', 't', 'rabbit-face', 'Bunny', 'Зайка', 2],
    ['pig-face', 't', 'pig-face', 'Piggy', 'Хрюшка', 2],
    ['house-with-garden', 'f', 'house-with-garden', 'Cottage', 'Домик', 3],
    ['no-national-park', 'n', 'national-park', 'National Park', 'Национальный парк', 3],
    ['no-sunrise-mountains', 'n', 'sunrise-over-mountains', 'Sunrise in the Mountains', 'Рассвет в горах', 3],
    ['no-house-garden', 'n', 'house-with-garden', 'Cottage with a Garden', 'Домик с садом', 3],
    ['no-tractor', 'n', 'tractor', 'Tractor', 'Трактор', 3],
    ['no-rooster', 'n', 'rooster', 'Rooster', 'Петушок', 3],
    ['no-peacock', 'n', 'peacock', 'Peacock', 'Павлин', 3],
  ],
  forest: [
    ['evergreen-tree', 'f', 'evergreen-tree', 'Fir Tree', 'Ёлка', 1],
    ['deciduous-tree', 'f', 'deciduous-tree', 'Tree', 'Дерево', 1],
    ['maple-leaf', 'f', 'maple-leaf', 'Maple Leaf', 'Кленовый лист', 1],
    ['chestnut', 'f', 'chestnut', 'Chestnut', 'Каштан', 1],
    ['brown-mushroom', 'f', 'brown-mushroom', 'Mushroom', 'Грибок', 1],
    ['mushroom', 't', 'mushroom', 'Toadstool', 'Мухомор', 1],
    ['tent', 'f', 'tent', 'Tent', 'Палатка', 2],
    ['koala', 'f', 'koala', 'Koala', 'Коала', 1],
    ['snake', 't', 'snake', 'Snake', 'Змейка', 1],
    ['t-rex', 'f', 't-rex', 'T-Rex', 'Тираннозавр', 1],
    ['sauropod', 'f', 'sauropod', 'Dino', 'Динозаврик', 1],
    ['fox', 'f', 'fox', 'Fox', 'Лисичка', 2],
    ['tw-fox', 't', 'fox', 'Red Fox', 'Лиса', 2],
    ['bear', 'f', 'bear', 'Bear', 'Мишка', 2],
    ['tw-owl', 't', 'owl', 'Owl', 'Сова', 2],
    ['hedgehog', 'f', 'hedgehog', 'Hedgehog', 'Ёжик', 2],
    ['raccoon', 'f', 'raccoon', 'Raccoon', 'Енот', 2],
    ['chipmunk', 'f', 'chipmunk', 'Chipmunk', 'Бурундук', 2],
    ['bird', 't', 'bird', 'Bird', 'Птичка', 2],
    ['tw-wolf', 't', 'wolf', 'Wolf', 'Волк', 2],
    ['boar', 'f', 'boar', 'Boar', 'Кабан', 2],
    ['moose', 'f', 'moose', 'Moose', 'Лось', 2],
    ['panda', 't', 'panda', 'Panda', 'Панда', 2],
    ['monkey-face', 'f', 'monkey-face', 'Monkey', 'Обезьянка', 2],
    ['tiger-face', 't', 'tiger-face', 'Tiger', 'Тигр', 2],
    ['lion', 'f', 'lion', 'Lion', 'Лев', 2],
    ['turtle', 't', 'turtle', 'Turtle', 'Черепаха', 2],
    ['fallen-leaf', 'f', 'fallen-leaf', 'Autumn Leaves', 'Листопад', 2],
    ['stump', 'f', 'wood', 'Stump', 'Пенёк', 2],
    ['nest-with-eggs', 'f', 'nest-with-eggs', 'Nest', 'Гнёздышко', 2],
    ['camping', 'f', 'camping', 'Camping', 'Поход', 3],
    ['bison', 'f', 'bison', 'Bison', 'Бизон', 3],
    ['no-camping', 'n', 'camping', 'Camping', 'Кемпинг', 3],
    ['no-owl', 'n', 'owl', 'Wise Owl', 'Мудрая сова', 2],
    ['no-hedgehog', 'n', 'hedgehog', 'Hedgehog', 'Ёжик', 2],
    ['no-deer', 'n', 'deer', 'Deer', 'Оленёнок', 2],
    ['no-fox', 'n', 'fox', 'Red Fox', 'Рыжий лис', 2],
    ['no-beaver', 'n', 'beaver', 'Beaver', 'Бобр', 2],
    ['no-bison', 'n', 'bison', 'Bison', 'Зубр', 2],
  ],
  sea: [
    ['fish', 'f', 'fish', 'Fish', 'Рыбка', 1],
    ['dolphin', 'f', 'dolphin', 'Dolphin', 'Дельфин', 1],
    ['tw-whale', 't', 'spouting-whale', 'Whale', 'Кит', 1],
    ['octopus', 't', 'octopus', 'Octopus', 'Осьминог', 1],
    ['crab', 'f', 'crab', 'Crab', 'Краб', 1],
    ['water-wave', 'f', 'water-wave', 'Wave', 'Волна', 1],
    ['ring-buoy', 'f', 'ring-buoy', 'Lifebuoy', 'Спасательный круг', 1],
    ['flip-flops', 'f', 'thong-sandal', 'Flip-Flops', 'Шлёпанцы', 1],
    ['swimsuit', 'f', 'one-piece-swimsuit', 'Swimsuit', 'Купальник', 1],
    ['tropical-fish', 'f', 'tropical-fish', 'Tropical Fish', 'Тропическая рыбка', 2],
    ['tw-tropical-fish', 't', 'tropical-fish', 'Angelfish', 'Рыба-ангел', 2],
    ['blowfish', 'f', 'blowfish', 'Pufferfish', 'Рыба-шар', 2],
    ['whale', 'f', 'spouting-whale', 'Baby Whale', 'Китёнок', 2],
    ['shark', 't', 'shark', 'Shark', 'Акула', 2],
    ['squid', 'f', 'squid', 'Squid', 'Кальмар', 2],
    ['lobster', 'f', 'lobster', 'Lobster', 'Омар', 2],
    ['shrimp', 'f', 'shrimp', 'Shrimp', 'Креветка', 2],
    ['jellyfish', 't', 'jellyfish', 'Jellyfish', 'Медуза', 2],
    ['coral', 'f', 'coral', 'Coral', 'Коралл', 2],
    ['spiral-shell', 'f', 'spiral-shell', 'Seashell', 'Ракушка', 2],
    ['sailboat', 'f', 'sailboat', 'Sailboat', 'Парусник', 2],
    ['beach', 'f', 'beach-with-umbrella', 'Beach', 'Пляж', 2],
    ['diving-mask', 'f', 'diving-mask', 'Snorkel', 'Маска с трубкой', 2],
    ['beach-umbrella', 't', 'umbrella-on-ground', 'Beach Umbrella', 'Зонтик', 2],
    ['palm-tree', 'f', 'palm-tree', 'Palm Tree', 'Пальма', 2],
    ['flamingo', 'f', 'flamingo', 'Flamingo', 'Фламинго', 2],
    ['orca', 't', 'orca', 'Orca', 'Косатка', 2],
    ['tropical-drink', 'f', 'tropical-drink', 'Cocktail', 'Коктейль', 2],
    ['water-lily', 'f', 'lotus', 'Water Lily', 'Кувшинка', 2],
    ['desert-island', 'f', 'desert-island', 'Island', 'Остров', 3],
    ['pearl', 'f', 'oyster', 'Pearl', 'Жемчужина', 3],
    ['no-desert-island', 'n', 'desert-island', 'Desert Island', 'Необитаемый остров', 3],
    ['no-beach', 'n', 'beach-with-umbrella', 'Beach Umbrella', 'Пляжный зонтик', 3],
    ['no-lighthouse', 'n', 'lighthouse', 'Lighthouse', 'Маяк', 3],
    ['no-sunrise', 'n', 'sunrise', 'Sunrise over the Sea', 'Восход над морем', 3],
    ['no-octopus', 'n', 'octopus', 'Octopus', 'Осьминог', 2],
    ['no-crab', 'n', 'crab', 'Crab', 'Краб', 2],
    ['no-tropical-fish', 'n', 'tropical-fish', 'Tropical Fish', 'Тропическая рыбка', 3],
    ['no-blowfish', 'n', 'blowfish', 'Pufferfish', 'Рыба-ёж', 3],
    ['no-shark', 'n', 'shark', 'Shark', 'Акула', 2],
    ['no-whale', 'n', 'spouting-whale', 'Spouting Whale', 'Кит с фонтаном', 3],
    ['no-turtle', 'n', 'turtle', 'Sea Turtle', 'Черепашка', 2],
    ['no-jellyfish', 'n', 'jellyfish', 'Jellyfish', 'Медуза', 3],
    ['no-coral', 'n', 'coral', 'Coral Reef', 'Коралл', 3],
    ['no-flamingo', 'n', 'flamingo', 'Flamingo', 'Фламинго', 2],
    ['no-parrot', 'n', 'parrot', 'Parrot', 'Попугай', 3],
  ],
  sweets: [
    ['doughnut', 'f', 'doughnut', 'Donut', 'Пончик', 2],
    ['cookie', 'f', 'cookie', 'Cookie', 'Печенье', 1],
    ['tw-lollipop', 't', 'lollipop', 'Lollipop', 'Леденец', 2],
    ['candy', 'f', 'candy', 'Candy', 'Конфета', 1],
    ['tw-candy', 't', 'candy', 'Mint Candy', 'Мятная конфета', 2],
    ['ice-cream-cone', 't', 'soft-ice-cream', 'Ice Cream Cone', 'Рожок', 1],
    ['cheese-wedge', 't', 'cheese-wedge', 'Cheese', 'Сыр', 1],
    ['pizza', 't', 'pizza', 'Pizza', 'Пицца', 1],
    ['rice-ball', 't', 'rice-ball', 'Onigiri', 'Онигири', 1],
    ['dango', 't', 'dango', 'Dango', 'Данго', 1],
    ['teapot', 'f', 'teapot', 'Teapot', 'Чайник', 1],
    ['drumstick', 'f', 'poultry-leg', 'Drumstick', 'Куриная ножка', 1],
    ['tw-doughnut', 't', 'doughnut', 'Glazed Donut', 'Пончик с глазурью', 2],
    ['cupcake', 'f', 'cupcake', 'Cupcake', 'Капкейк', 2],
    ['birthday-cake', 't', 'birthday-cake', 'Birthday Cake', 'Торт', 2],
    ['shortcake', 'f', 'shortcake', 'Cake Slice', 'Кусочек торта', 2],
    ['lollipop', 'f', 'lollipop', 'Rainbow Lollipop', 'Радужный леденец', 3],
    ['chocolate-bar', 'f', 'chocolate-bar', 'Chocolate', 'Шоколадка', 2],
    ['sundae', 't', 'ice-cream', 'Sundae', 'Мороженое', 2],
    ['shaved-ice', 'f', 'shaved-ice', 'Shaved Ice', 'Фруктовый лёд', 2],
    ['pudding', 't', 'custard', 'Pudding', 'Пудинг', 2],
    ['pie', 't', 'pie', 'Pie', 'Пирог', 2],
    ['honey-pot', 'f', 'honey-pot', 'Honey', 'Мёд', 2],
    ['pancakes', 'f', 'pancakes', 'Pancakes', 'Блинчики', 2],
    ['hamburger', 'f', 'hamburger', 'Burger', 'Бургер', 2],
    ['hot-dog', 't', 'hot-dog', 'Hot Dog', 'Хот-дог', 2],
    ['french-fries', 'f', 'french-fries', 'Fries', 'Картошка фри', 2],
    ['taco', 'f', 'taco', 'Taco', 'Тако', 2],
    ['popcorn', 'f', 'popcorn', 'Popcorn', 'Попкорн', 2],
    ['fried-egg', 'f', 'cooking', 'Fried Egg', 'Яичница', 2],
    ['sushi', 't', 'sushi', 'Sushi', 'Суши', 3],
    ['sandwich', 'f', 'sandwich', 'Sandwich', 'Бутерброд', 3],
    ['no-birthday-cake', 'n', 'birthday-cake', 'Birthday Cake', 'Праздничный торт', 3],
    ['no-shortcake', 'n', 'shortcake', 'Strawberry Cake', 'Клубничный торт', 3],
    ['no-cupcake', 'n', 'cupcake', 'Cupcake', 'Капкейк', 3],
    ['no-chocolate', 'n', 'chocolate-bar', 'Chocolate Bar', 'Шоколадка', 2],
    ['no-doughnut', 'n', 'doughnut', 'Sprinkle Doughnut', 'Пончик с посыпкой', 3],
    ['no-cookie', 'n', 'cookie', 'Chocolate Chip Cookie', 'Печенье с шоколадом', 2],
    ['no-ice-cream', 'n', 'ice-cream', 'Sundae', 'Мороженое в креманке', 3],
    ['no-shaved-ice', 'n', 'shaved-ice', 'Snow Cone', 'Фруктовый лёд', 3],
    ['no-honey-pot', 'n', 'honey-pot', 'Honey Pot', 'Горшочек мёда', 2],
    ['no-pancakes', 'n', 'pancakes', 'Pancake Stack', 'Стопка блинчиков', 2],
    ['no-bento', 'n', 'bento-box', 'Bento Box', 'Бэнто', 3],
    ['no-dango', 'n', 'dango', 'Dango', 'Данго', 2],
  ],
  space: [
    ['alien', 'f', 'alien', 'Alien', 'Инопланетянин', 1],
    ['alien-monster', 'f', 'alien-monster', 'Space Invader', 'Космический монстр', 1],
    ['earth', 'f', 'globe-showing-americas', 'Earth', 'Земля', 1],
    ['tw-earth', 't', 'globe-showing-europe-africa', 'Planet Earth', 'Планета Земля', 1],
    ['full-moon', 'f', 'full-moon', 'Full Moon', 'Полная луна', 1],
    ['half-moon', 'f', 'first-quarter-moon', 'Half Moon', 'Половинка луны', 1],
    ['crescent-moon', 'f', 'crescent-moon', 'Crescent Moon', 'Месяц', 1],
    ['moon-face', 't', 'full-moon-face', 'Moon Face', 'Луна с улыбкой', 1],
    ['glowing-star', 't', 'glowing-star', 'Star', 'Звёздочка', 1],
    ['twinkles', 't', 'sparkles', 'Twinkles', 'Искорки', 1],
    ['dizzy', 't', 'dizzy', 'Spinning Star', 'Кружащая звезда', 1],
    ['bat', 'f', 'bat', 'Bat', 'Летучая мышь', 1],
    ['thunder-cloud', 'f', 'cloud-with-lightning', 'Thunder Cloud', 'Грозовая туча', 1],
    ['rocket', 'f', 'rocket', 'Rocket', 'Ракета', 2],
    ['tw-rocket', 't', 'rocket', 'Blue Rocket', 'Синяя ракета', 2],
    ['ufo', 'f', 'flying-saucer', 'Flying Saucer', 'Летающая тарелка', 2],
    ['tw-ufo', 't', 'flying-saucer', 'UFO', 'НЛО', 2],
    ['robot', 'f', 'robot', 'Robot', 'Робот', 2],
    ['tw-robot', 't', 'robot', 'Retro Robot', 'Ретро-робот', 2],
    ['ringed-planet', 'f', 'ringed-planet', 'Saturn', 'Сатурн', 2],
    ['tw-ringed-planet', 't', 'ringed-planet', 'Ringed Planet', 'Планета с кольцами', 2],
    ['sun-with-face', 'f', 'sun-with-face', 'Smiling Sun', 'Солнце', 2],
    ['shooting-star', 't', 'shooting-star', 'Shooting Star', 'Падающая звезда', 2],
    ['comet', 't', 'comet', 'Comet', 'Комета', 2],
    ['telescope', 't', 'telescope', 'Telescope', 'Телескоп', 2],
    ['owl', 'f', 'owl', 'Night Owl', 'Совушка', 2],
    ['black-cat', 't', 'black-cat', 'Black Cat', 'Чёрный кот', 2],
    ['milky-way', 'f', 'milky-way', 'Milky Way', 'Млечный путь', 2],
    ['night-city', 'f', 'night-with-stars', 'Night City', 'Ночной город', 3],
    ['night-bridge', 't', 'bridge-at-night', 'Night Bridge', 'Ночной мост', 3],
    ['no-milky-way', 'n', 'milky-way', 'Milky Way', 'Млечный Путь', 3],
    ['no-night-stars', 'n', 'night-with-stars', 'Starry Night City', 'Звёздная ночь в городе', 3],
    ['no-city-dusk', 'n', 'cityscape-at-dusk', 'City at Dusk', 'Город в сумерках', 3],
    ['no-night-bridge', 'n', 'bridge-at-night', 'Bridge at Night', 'Мост ночью', 3],
    ['no-city-sunset', 'n', 'sunset', 'City Sunset', 'Закат над городом', 3],
    ['no-rocket', 'n', 'rocket', 'Rocket', 'Ракета', 3],
    ['no-flying-saucer', 'n', 'flying-saucer', 'Flying Saucer', 'Летающая тарелка', 3],
    ['no-saturn', 'n', 'ringed-planet', 'Saturn', 'Сатурн', 3],
    ['no-satellite', 'n', 'satellite', 'Satellite', 'Спутник', 3],
    ['no-robot', 'n', 'robot', 'Robot', 'Робот', 2],
    ['no-astronaut', 'n', 'astronaut', 'Astronaut', 'Космонавт', 3],
  ],
  winter: [
    ['gift', 'f', 'wrapped-gift', 'Gift', 'Подарок', 1],
    ['tw-gift', 't', 'wrapped-gift', 'Present', 'Подарочек', 1],
    ['scarf', 'f', 'scarf', 'Scarf', 'Шарф', 1],
    ['puffer-jacket', 't', 'coat', 'Puffer Jacket', 'Пуховик', 1],
    ['mittens', 'f', 'gloves', 'Mittens', 'Варежки', 1],
    ['socks', 't', 'socks', 'Socks', 'Носочки', 1],
    ['curling-stone', 'f', 'curling-stone', 'Curling Stone', 'Кёрлинг', 1],
    ['ice-cube', 'f', 'ice', 'Ice Cube', 'Льдинка', 1],
    ['penguin', 'f', 'penguin', 'Penguin', 'Пингвин', 1],
    ['tw-penguin', 't', 'penguin', 'Emperor Penguin', 'Пингвинчик', 1],
    ['candle', 'f', 'candle', 'Candle', 'Свеча', 1],
    ['bell', 'f', 'bell', 'Bell', 'Колокольчик', 1],
    ['ribbon', 'f', 'ribbon', 'Bow', 'Бантик', 1],
    ['lantern', 'f', 'red-paper-lantern', 'Lantern', 'Фонарик', 1],
    ['hut', 'f', 'hut', 'Hut', 'Хижина', 1],
    ['yarn', 't', 'yarn', 'Yarn Ball', 'Клубок', 2],
    ['snowman', 'f', 'snowman-without-snow', 'Snowman', 'Снеговик', 2],
    ['tw-snowman', 't', 'snowman-without-snow', 'Snowman in Hat', 'Снеговик в шляпе', 2],
    ['christmas-tree', 'f', 'christmas-tree', 'Christmas Tree', 'Новогодняя ёлка', 3],
    ['sled', 'f', 'sled', 'Sled', 'Санки', 2],
    ['ice-skate', 'f', 'ice-skate', 'Ice Skate', 'Конёк', 2],
    ['polar-bear', 't', 'polar-bear', 'Polar Bear', 'Белый медведь', 2],
    ['reindeer', 't', 'deer', 'Reindeer', 'Олень', 2],
    ['seal', 'f', 'seal', 'Seal', 'Тюлень', 2],
    ['snowy-mountain', 'f', 'snow-capped-mountain', 'Snowy Mountain', 'Снежная гора', 2],
    ['house', 'f', 'house', 'Cozy House', 'Уютный дом', 2],
    ['matryoshka', 'f', 'nesting-dolls', 'Matryoshka', 'Матрёшка', 2],
    ['teddy-bear', 't', 'teddy-bear', 'Teddy Bear', 'Плюшевый мишка', 2],
    ['mantel-clock', 'f', 'mantelpiece-clock', 'Clock', 'Часы', 2],
    ['wolf', 'f', 'wolf', 'Grey Wolf', 'Серый волк', 2],
    ['white-hare', 'f', 'rabbit', 'White Hare', 'Заяц-беляк', 2],
    ['no-snowy-peak', 'n', 'snow-capped-mountain', 'Snowy Peak', 'Снежная вершина', 3],
    ['no-cable-car', 'n', 'mountain-cableway', 'Cable Car', 'Канатная дорога', 3],
    ['no-snowman', 'n', 'snowman', 'Snowman', 'Снеговик', 2],
    ['no-skier', 'n', 'skier', 'Skier', 'Лыжник', 3],
    ['no-christmas-tree', 'n', 'christmas-tree', 'Christmas Tree', 'Ёлочка', 3],
    ['no-penguin', 'n', 'penguin', 'Penguin', 'Пингвин', 2],
    ['no-santa', 'n', 'santa-claus', 'Santa Claus', 'Дед Мороз', 3],
  ],
  fantasy: [
    ['crown', 'f', 'crown', 'Crown', 'Корона', 1],
    ['gem-stone', 'f', 'gem-stone', 'Gem', 'Самоцвет', 1],
    ['tw-gem-stone', 't', 'gem-stone', 'Diamond', 'Бриллиант', 1],
    ['crystal-ball', 'f', 'crystal-ball', 'Crystal Ball', 'Хрустальный шар', 1],
    ['tw-crystal-ball', 't', 'crystal-ball', 'Magic Orb', 'Волшебный шар', 1],
    ['shield', 'f', 'shield', 'Shield', 'Щит', 1],
    ['golden-key', 'f', 'old-key', 'Golden Key', 'Золотой ключик', 1],
    ['scroll', 't', 'scroll', 'Scroll', 'Свиток', 1],
    ['trophy', 'f', 'trophy', 'Trophy', 'Кубок', 1],
    ['hourglass', 't', 'hourglass-not-done', 'Hourglass', 'Песочные часы', 1],
    ['magic-mirror', 'f', 'mirror', 'Magic Mirror', 'Волшебное зеркало', 1],
    ['jack-o-lantern', 't', 'jack-o-lantern', 'Pumpkin', 'Тыква', 1],
    ['tw-unicorn', 't', 'unicorn-face', 'Unicorn', 'Единорог', 2],
    ['sparkling-heart', 'f', 'sparkling-heart', 'Magic Heart', 'Волшебное сердце', 1],
    ['tw-ghost', 't', 'ghost', 'Boo', 'Бу-призрак', 1],
    ['dragon-face', 'f', 'dragon-face', 'Dragon', 'Дракончик', 2],
    ['tw-dragon-face', 't', 'dragon-face', 'Green Dragon', 'Зелёный дракон', 2],
    ['tw-dragon', 't', 'dragon', 'Dragon', 'Дракон', 2],
    ['unicorn', 'f', 'unicorn', 'Rainbow Unicorn', 'Радужный единорог', 2],
    ['tw-crown', 't', 'crown', 'Royal Crown', 'Королевская корона', 2],
    ['castle', 'f', 'castle', 'Castle', 'Замок', 2],
    ['japanese-castle', 'f', 'japanese-castle', 'Japanese Castle', 'Японский замок', 2],
    ['magic-broom', 't', 'broom', 'Magic Broom', 'Волшебная метла', 2],
    ['ghost', 'f', 'ghost', 'Ghost', 'Привидение', 2],
    ['crossed-swords', 't', 'crossed-swords', 'Swords', 'Мечи', 2],
    ['carousel-horse', 'f', 'carousel-horse', 'Carousel Horse', 'Лошадка', 2],
    ['circus-tent', 'f', 'circus-tent', 'Circus', 'Цирк', 2],
    ['magic-hat', 'f', 'top-hat', 'Magic Hat', 'Шляпа фокусника', 2],
    ['heart-with-ribbon', 'f', 'heart-with-ribbon', 'Heart Gift', 'Сердце с бантом', 2],
    ['dragon', 'f', 'dragon', 'Chinese Dragon', 'Китайский дракон', 3],
    ['phoenix', 'f', 'phoenix-bird', 'Phoenix', 'Феникс', 3],
    ['no-castle', 'n', 'castle', 'Fairy-tale Castle', 'Сказочный замок', 3],
    ['no-japanese-castle', 'n', 'japanese-castle', 'Japanese Castle', 'Японский замок', 3],
    ['no-ferris-wheel', 'n', 'ferris-wheel', 'Ferris Wheel', 'Колесо обозрения', 3],
    ['no-roller-coaster', 'n', 'roller-coaster', 'Roller Coaster', 'Американские горки', 3],
    ['no-carousel', 'n', 'carousel-horse', 'Carousel Horse', 'Карусельная лошадка', 3],
    ['no-circus', 'n', 'circus-tent', 'Circus Tent', 'Цирковой шатёр', 3],
    ['no-fireworks', 'n', 'fireworks', 'Fireworks', 'Салют', 3],
    ['no-moon-viewing', 'n', 'moon-viewing-ceremony', 'Moon Festival', 'Праздник луны', 3],
    ['no-unicorn', 'n', 'unicorn', 'Unicorn', 'Единорог', 3],
    ['no-dragon', 'n', 'dragon', 'Dragon', 'Дракон', 3],
    ['no-dragon-face', 'n', 'dragon-face', 'Dragon Face', 'Морда дракона', 3],
    ['no-wizard', 'n', 'mage', 'Wizard', 'Волшебник', 3],
    ['no-fairy', 'n', 'fairy', 'Fairy', 'Фея', 3],
    ['no-genie', 'n', 'genie', 'Genie', 'Джинн', 3],
    ['no-mermaid', 'n', 'merperson', 'Mermaid', 'Русалочка', 3],
    ['no-crystal-ball', 'n', 'crystal-ball', 'Crystal Ball', 'Хрустальный шар', 3],
    ['no-pumpkin', 'n', 'jack-o-lantern', 'Jack-o’-Lantern', 'Тыква-фонарь', 2],
    ['no-crown', 'n', 'crown', 'Jeweled Crown', 'Корона с камнями', 3],
    ['no-volcano', 'n', 'volcano', 'Volcano', 'Вулкан', 3],
  ],
};

export const THEMES: Theme[] = ['meadow', 'forest', 'sea', 'sweets', 'space', 'winter', 'fantasy'];

export const PICTURES: PictureEntry[] = THEMES.flatMap((theme) =>
  rows[theme].map(([id, src, icon, en, ru, complexity]) => ({
    id,
    source: src === 'f' ? ('fluent' as const) : src === 'n' ? ('noto' as const) : ('twemoji' as const),
    icon,
    theme,
    name: { en, ru },
    complexity,
  })),
);
